# Generated by Django 3.0.5 on 2020-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Apple', max_length=20)),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
